# Docker Compose file for Vapor
#
# Install Docker on your system to run and test
# your Vapor app in a production-like environment.
#
# Note: This file is intended for testing and does not
# implement best practices for a production deployment.
#
# Learn more: https://docs.docker.com/compose/reference/
#
#   Build images: docker-compose build
#      Start app: docker-compose up app
# Start database: docker-compose up db
# Run migrations: docker-compose run migrate
#       Stop all: docker-compose down (add -v to wipe db)
#
version: '3.7'

volumes:
  db_data:

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  DATABASE_HOST: db
  DATABASE_NAME: vapor_database
  DATABASE_USERNAME: vapor_username
  
services:
  app:
    image: 1kbwc:latest
    build:
      context: .
    environment:
      <<: *shared_environment
      DATABASE_PASSWORD_FILE: /run/secrets/pg-password
    depends_on:
      - db
    networks:
      - backend
    ports:
      - '8080:8080'
    # user: '0' # uncomment to run as root for testing purposes even though Dockerfile defines 'vapor' user.
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
    secrets:
      - pg-password
  migrate:
    image: 1kbwc:latest
    build:
      context: .
    networks:
      - backend
    environment:
      <<: *shared_environment
      DATABASE_PASSWORD_FILE: /run/secrets/pg-password
    depends_on:
      - db
    command: ["migrate", "--yes"]
    deploy:
      replicas: 0
    secrets:
      - pg-password
  revert:
    image: 1kbwc:latest
    build:
      context: .
    networks:
      - backend
    environment:
      <<: *shared_environment
      DATABASE_PASSWORD_FILE: /run/secrets/pg-password
    depends_on:
      - db
    command: ["migrate", "--revert", "--yes"]
    deploy:
      replicas: 0
    secrets:
      - pg-password
  db:
    image: postgres:14-alpine
    networks:
      - backend
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: vapor_username
      POSTGRES_PASSWORD_FILE: /run/secrets/pg-password
      POSTGRES_DB: vapor_database
    ports:
      - '5432:5432'
    secrets:
      - pg-password
  nginx:
    image: my-nginx:latest
    build:
      context: ./nginx
    container_name: nginx
    depends_on:
      - app
    networks:
      - backend
    environment:
      - NGINX_PORT=80
    ports:
      - '80:80'

networks:
    backend:

secrets:
  pg-password:
    file: ./secrets/pg_password.txt
