version: '3.7'

services:
  app:
    container_name: app-prod
    env_file:
      - ./env/.env.prod
  db:
    container_name: db-prod
  nginx:
    env_file:
      - ./env/.env.nginx.prod
    container_name: nginx-prod
  redis:
    container_name: redis-prod