version: '3.7'

services:
  app:
    container_name: app-prod
    env_file:
      - ./env/.env.prod
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
  migrate:
    env_file:
      - ./env/.env.prod
  revert:
    env_file:
      - ./env/.env.prod
  routes:
    env_file:
      - ./env/.env.prod
  db:
    container_name: db-prod
  nginx:
    env_file:
      - ./env/.env.nginx.prod
    container_name: nginx-prod
    volumes:
      - ./nginx/certbot:/etc/letsencrypt:ro
      - ./nginx/certbot/www:/var/www/certbot:ro
  redis:
    container_name: redis-prod