version: '3.7'

services:
  app:
    container_name: app-dev
    env_file:
      - ./env/.env.dev
    command: ["serve", "--env", "development", "--hostname", "0.0.0.0", "--port", "8080"]
  migrate:
    secrets:
      - admin-user
      - admin-password
    environment:
      ADMIN_USERNAME_FILE: /run/secrets/admin-user
      ADMIN_PASSWORD_FILE: /run/secrets/admin-password
    env_file:
      - ./env/.env.dev
  revert:
    secrets:
      - admin-user
      - admin-password
    environment:
      ADMIN_USERNAME_FILE: /run/secrets/admin-user
      ADMIN_PASSWORD_FILE: /run/secrets/admin-password
    env_file:
      - ./env/.env.dev
  routes:
    env_file:
      - ./env/.env.dev
  db:
    container_name: db-dev
  nginx:
    env_file:
      - ./env/.env.nginx.dev
    container_name: nginx-dev
    volumes:
      - ./nginx/certbot:/etc/letsencrypt:ro
      - ./nginx/certbot/www:/var/www/certbot:ro
  redis:
    container_name: redis-dev
  