version: '3.7'

services:
  app:
    container_name: app-dev
    env_file:
      - ./env/.env.dev
    command: ["serve", "--env", "development", "--hostname", "0.0.0.0", "--port", "8080"]
  migrate:
    env_file:
      - ./env/.env.dev
  revert:
    env_file:
      - ./env/.env.dev
  routes:
    env_file:
      - ./env/.env.dev
  db:
    container_name: db-dev
  nginx:
    env_file:
      - ./env/.env.nginx.dev
    container_name: nginx-dev
  redis:
    container_name: redis-dev
  