version: '3.7'

services:
  app:
    container_name: app-dev
    env_file:
      - ./env/.env.dev
  db:
    container_name: db-dev
  nginx:
    env_file:
      - ./env/.env.nginx.dev
    container_name: nginx-dev
  redis:
    container_name: redis-dev